
service: lane-api-001
frameworkVersion: '2'
useDotenv: true

plugins:
    - serverless-python-requirements
    - serverless-wsgi

custom:
    wsgi:
        app: server.app
        packRequirements: false
    pythonRequirements:
        dockerizePip: false


provider:
    name: aws
    runtime: python3.7
    lambdaHashingVersion: 20201221
    region: ap-northeast-1
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                  Resource: 'arn:aws:dynamodb:ap-northeast-1:*:*'
                - Effect: Allow
                  Action:
                      - s3:PutObject
                  Resource: 'arn:aws:s3:::*'

functions:
    app:
        handler: wsgi.handler
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
        environment:
            LANE_API_URL: ${env:LANE_API_URL}
            DB_NAME: ${env:DB_NAME}
            BUCKET_NAME: ${env:BUCKET_NAME}
            S3_USER_KEY: ${env:S3_USER_KEY}
            S3_MEDIA_KEY: ${env:S3_MEDIA_KEY}
            CF_HOST_NAME: ${env:CF_HOST_NAME}
            GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
        timeout: 30

